version: '3'
services:
  nginx:
    image: server-nginx
    volumes:
      - ./log:/var/log/nginx
      - ./public:/usr/share/nginx/html
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
